# Generated by Django 5.0.4 on 2024-05-02 11:14

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetail',
            name='Address',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='Phone_number',
            field=models.IntegerField(),
        ),
    ]