# Generated by Django 5.0.4 on 2024-05-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0003_ajents'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajents',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ajents',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
