# Generated by Django 5.0.4 on 2024-05-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0005_ajents_phone_ajents_end_time_ajents_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajents',
            name='end_Time',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ajents',
            name='start_Time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
