# Generated by Django 5.0.4 on 2024-05-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0007_remove_ajents_phone_remove_ajents_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('agent_name', models.CharField(max_length=255)),
                ('agent_number', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('approval', models.BooleanField(default=False)),
                ('time_slot', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='AgentAvailability',
        ),
    ]
