# Generated by Django 5.0.4 on 2024-05-22 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0008_appointment_delete_agentavailability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
