# Generated by Django 5.0.4 on 2024-05-22 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0010_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
