# Generated by Django 5.0.4 on 2024-05-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0016_remove_customerdetail_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetail',
            name='Address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='Phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
