# Generated by Django 5.0.4 on 2024-05-29 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0018_category_policy_policyrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='category',
        ),
        migrations.RemoveField(
            model_name='policyrecord',
            name='Policy',
        ),
        migrations.RemoveField(
            model_name='policyrecord',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Policy',
        ),
        migrations.DeleteModel(
            name='PolicyRecord',
        ),
    ]
