# Generated by Django 5.0.4 on 2024-05-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0021_policyapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyapplication',
            name='payment_details',
            field=models.TextField(null=True),
        ),
    ]
