# Generated by Django 5.0.4 on 2024-05-29 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0022_policyapplication_payment_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policyapplication',
            name='payment_details',
        ),
    ]
