# Generated by Django 5.0.4 on 2024-05-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0023_remove_policyapplication_payment_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetail',
            name='otp',
            field=models.CharField(default='0000', max_length=25),
        ),
    ]
